# Generated by Django 3.0.4 on 2020-03-28 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameDetails',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('real_name', models.CharField(blank=True, max_length=32, null=True)),
                ('time_zone', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.NameDetails')),
            ],
        ),
    ]
