# Generated by Django 3.0.4 on 2020-03-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_namedetails_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namedetails',
            old_name='time_zone',
            new_name='tz',
        ),
        migrations.DeleteModel(
            name='ActivityPeriod',
        ),
    ]
